name: tests

on:
  push:
    branches:
      - '*'

  pull_request:
    branches:
      - '*'

env:
  CACHE_NUMBER: 0  # edit this to trigger new chaching manually

jobs:
  cache-env-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install ffmpeg
        run: sudo apt-get install -y ffmpeg

      - uses: actions/checkout@v2
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
            miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: mp-transformer
            use-mamba: true

      # Caching the environment if environment.yml has changed
      - uses: actions/cache@v2
        id: cache
        with:
          path: /usr/share/miniconda3/envs/mp-transformer
          key: ubuntu-conda-${{ hashFiles('environment.yml') }}-${{ env.CACHE_NUMBER }}

      - name: Update environment
        run: mamba env update -n mp-transformer -f environment.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        shell: bash -l {0} # login shell due to conda env
        run: python -m unittest discover -s unittests
